services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Asia/Dubai}
      # JELLYFIN_PublishedServerUrl=192.168.0.5 # Optional: Set your server IP
    volumes:
      - ${CONFIG_DIR}/jellyfin/config:/config
      - ${CONFIG_DIR}/jellyfin/cache:/cache
      - ${MEDIA_DIR}:/data/media
    ports:
      - 8096:8096
      - 1900:1900/udp # DLNA
      - 7359:7359/udp # Local network discovery
    restart: unless-stopped
    network_mode: host

